stages:
  # TODO: Add tests and configure test stage.
  # - test
  - build
  # - deploy

build:
  only:
    refs:
      # - develop
      - master
  stage: build
  # image: node:14.16.0-buster
  # before_script:
  #   - curl -f https://get.pnpm.io/v6.7.js | node - add --global pnpm@6
  #   - pnpm config set store-dir .pnpm-store
  script:
    - cd ./scripts
    - ./build_multi-stage.sh
